import { Track, Genre, MainGenre } from '@/types';

interface SongEntry {
  artist: string;
  title: string;
  isAlbum: boolean;
}

const parseSongEntries = (): SongEntry[] => {
  const entries: SongEntry[] = [
    { artist: 'Sara Noxx & Mark Benecke', title: 'Jeanny', isAlbum: false },
    { artist: 'Rotersand', title: 'Torn Realities', isAlbum: false },
    { artist: 'In Strict Confidence', title: "Somebody Else's Dream", isAlbum: false },
    { artist: 'SONO', title: 'Cupid', isAlbum: false },
    { artist: 'Pink Turns Blue', title: 'The AERDT - Untold Stories', isAlbum: false },
    { artist: ':Wumpscut:', title: 'DJ Dwarf 16', isAlbum: false },
    { artist: 'Welle: Erdball', title: '1000 Engel', isAlbum: false },
    { artist: 'Iggy Pop', title: 'Gardenia', isAlbum: false },
    { artist: 'Decoded Feedback', title: 'Waiting For The Storm', isAlbum: false },
    { artist: '8KIDS', title: 'Dämonen', isAlbum: false },
    { artist: 'Biffy Clyro', title: 'Wolves of Winter', isAlbum: false },
    { artist: 'The Cult', title: 'Goat', isAlbum: false },
    { artist: 'Rob Zombie', title: 'In The Age Of Consecrated Vampire We All Get High', isAlbum: false },
    { artist: 'ASP', title: 'Souvenir, Souvenir', isAlbum: false },
    { artist: 'New Order', title: 'Singularity', isAlbum: false },
    { artist: 'Pet Shop Boys', title: 'The Pop Kids', isAlbum: false },
    { artist: 'RROYCE', title: 'The Principle Of Grace', isAlbum: false },
    { artist: 'In Good Faith', title: 'Shadows', isAlbum: false },
    { artist: 'Inertia', title: 'Distant Mind', isAlbum: false },
    { artist: 'Zweite Jugend', title: 'Hoch die Tassen', isAlbum: false },
    { artist: 'Crematory', title: 'Ravens Calling', isAlbum: false },
    { artist: 'Bosse', title: 'Steine', isAlbum: false },
    { artist: 'AnnenMayKantereit', title: 'Pocahontas', isAlbum: false },
    { artist: 'Sara Noxx', title: 'Die Liebe', isAlbum: false },
    { artist: 'diorama', title: 'the same ghost', isAlbum: false },
    { artist: 'In Mitra Medusa Inri', title: 'Memories', isAlbum: false },
    { artist: 'Lakeside X', title: 'Factory Flowers', isAlbum: false },
    { artist: 'Mesh', title: 'Hey Stranger', isAlbum: false },
    { artist: 'Baltes and Zaeyn', title: 'Neogodzilla vernichtet Metropolis', isAlbum: false },
    { artist: 'Fortification 55', title: 'Static Veil', isAlbum: false },
    { artist: 'Scheuber', title: 'Monument', isAlbum: false },
    { artist: 'Oasis', title: 'Falling Down', isAlbum: false },
    { artist: 'T!ANA', title: 'Be Silent', isAlbum: false },
    { artist: 'Dorian Black', title: 'Share my Desire', isAlbum: false },
    { artist: 'The Halo Trees', title: 'Sycamore Lane', isAlbum: false },
    { artist: 'Kopetti feat. KarL', title: 'Schwarze Sonne', isAlbum: false },
    { artist: 'Death Valley Fight Club', title: 'Inspired for Life', isAlbum: false },
    { artist: 'In Strict Confidence', title: 'Blasphemous Rumours', isAlbum: false },
    { artist: 'Hidden Souls', title: 'Something', isAlbum: false },
    { artist: 'Mängelexemplar', title: 'Neue Zukunft', isAlbum: false },
    { artist: 'Twin Noir', title: 'Luft für Dich', isAlbum: false },
    { artist: 'Schattenfrequenz', title: 'Feuer', isAlbum: false },
    { artist: 'Beyond Border', title: 'Prayer Club EP', isAlbum: false },
    { artist: 'Projekt JU feat. Butterfly K', title: 'You', isAlbum: false },
    { artist: 'Lightshifters', title: 'Absurdities', isAlbum: false },
    { artist: 'Flesh Field', title: 'Ballad of the Renegade', isAlbum: false },
    { artist: 'Machine Command', title: 'Decline and Rise again', isAlbum: false },
    { artist: 'Dawn of Ashes', title: 'Viral Decay', isAlbum: false },
    { artist: 'Lorning', title: 'Footprints', isAlbum: false },
    { artist: 'IAMX', title: 'Artificial Innocence', isAlbum: false },
    { artist: 'Raf Duran', title: 'Mortified', isAlbum: false },
    { artist: 'Diorama', title: 'Million Dollar Smile', isAlbum: false },
    { artist: 'Seelennacht', title: 'April Rain', isAlbum: false },
    { artist: 'Beyond Obsession', title: "You're Not My Lover", isAlbum: false },
    { artist: 'Look Mum No Computer', title: 'Eins, Zwei, Drei', isAlbum: false },
    { artist: 'Huir', title: 'You', isAlbum: false },
    { artist: 'Rebel Empire', title: 'Rebel Body Music', isAlbum: false },
    { artist: 'SYNTHATTACK', title: 'We Are SynthAttack 2.0', isAlbum: false },
    { artist: 'FREAKY MIND', title: 'On The Hook', isAlbum: false },
    { artist: 'BASSZILLA', title: 'Life is HARD', isAlbum: false },
    { artist: 'NEUROKLAST', title: 'GODSLAYER', isAlbum: false },
    { artist: 'DEAD LIGHTS', title: 'Killing Time', isAlbum: false },
    { artist: 'CIRCUIT PREACHER', title: 'This All Hurts', isAlbum: false },
    { artist: 'EXTIZE', title: 'Techno Viking', isAlbum: false },
    { artist: 'AGNIS', title: 'Gothess', isAlbum: false },
    { artist: 'HER OWN WORLD', title: 'Hapiness Imparative', isAlbum: false },
    { artist: 'OMNIMAR', title: 'The Matrix', isAlbum: false },
    { artist: 'BLACKBOOK', title: 'Eternal Glory', isAlbum: false },
    { artist: 'ANTIBODY x CZARINA x BINARY DIVISION', title: 'My Enemy', isAlbum: false },
    { artist: 'KYUNAA', title: 'Horns', isAlbum: false },
    { artist: 'DANCE MY DARLING', title: 'Criminal', isAlbum: false },
    { artist: 'APNOIE', title: 'Inadéquat', isAlbum: false },
    { artist: 'The Synthetic Dream Foundation', title: 'Unleashed', isAlbum: false },
    { artist: 'Informatik', title: 'My True Love', isAlbum: false },
    { artist: 'Autoclav1.1', title: 'Miags', isAlbum: false },
    { artist: 'E-Craft', title: 'Scan Error', isAlbum: false },
    { artist: 'Front Line Assembly', title: 'Burning Skyline', isAlbum: false },
    { artist: 'Gary Numan', title: 'resurrection', isAlbum: false },
    { artist: 'Hanzel und Gretyl', title: 'Robot Logik', isAlbum: false },
    { artist: 'Comaduster', title: 'The Shadowsphere', isAlbum: false },
    { artist: 'Porcelain And The Tramps', title: 'You Want', isAlbum: false },
    { artist: 'Omnimar', title: 'Boom Boom', isAlbum: false },
    { artist: 'Panzer AG', title: 'Sick is the One Who Adores Me', isAlbum: false },
    { artist: 'Necro Facility', title: 'You Want It', isAlbum: false },
    { artist: 'Mind in a Box', title: 'Machine Run', isAlbum: false },
    { artist: 'The Synthetic Dream Foundation', title: "Twilight's Dream", isAlbum: false },
    { artist: 'Aslan Faction', title: 'Soul Obstruction', isAlbum: false },
    { artist: 'Stendeck', title: 'Let Us Conversate Again', isAlbum: false },
    { artist: 'AL1CE', title: 'Wide Awake', isAlbum: false },
    { artist: 'Lucidstatic', title: 'Fakt', isAlbum: false },
    { artist: 'Zardonic and Voicians', title: 'Bring Back the Glory', isAlbum: false },
    { artist: 'Tweaker', title: 'Areas of the Brain', isAlbum: false },
    { artist: 'Diary Of Dreams', title: '06_Rebellion', isAlbum: false },
    { artist: 'Pleban', title: 'Minus 51', isAlbum: false },
    { artist: 'Project Pitchfork', title: 'The Circus', isAlbum: false },
    { artist: 'Agonoize', title: 'Labyrinth', isAlbum: false },
    { artist: 'Panzer AG', title: 'When Death Embrace Me', isAlbum: false },
    { artist: 'Totem Obscura', title: 'Waldgeist', isAlbum: false },
    { artist: 'Shadowplay', title: 'Out Of Control', isAlbum: false },
    { artist: 'Xylonite Ivy', title: 'Wonderful Ring', isAlbum: false },
    { artist: 'Bodanegra feat. Rio Black', title: 'Seide', isAlbum: false },
    { artist: 'NNHMN', title: 'Lovelorn', isAlbum: false },
    { artist: 'Maman Kusters', title: 'Träumen Androiden Von Elektrischen Schafen', isAlbum: false },
    { artist: 'Ministry', title: 'Thieves', isAlbum: false },
    { artist: 'Skinny Puppy', title: 'Stairs and Flowers', isAlbum: false },
    { artist: 'Messa', title: 'The Spin', isAlbum: true },
    { artist: 'Deafheaven', title: 'Lonely People With Power', isAlbum: true },
    { artist: 'Chat Pile & Hayden Pedigo', title: 'In the Earth Again', isAlbum: true },
    { artist: 'Der Weg einer Freiheit', title: 'Innern', isAlbum: true },
    { artist: 'Hedonist', title: 'Scapulimancy', isAlbum: true },
    { artist: 'Agriculture', title: 'The Spiritual Sound', isAlbum: true },
    { artist: 'Deftones', title: 'private music', isAlbum: true },
    { artist: 'Yellow Eyes', title: 'Confusion Gate', isAlbum: true },
    { artist: 'Starbynary', title: 'Romeo and Juliet Pt.', isAlbum: true },
    { artist: 'Stormbreaker', title: 'Enlightning', isAlbum: true },
    { artist: 'Front 242', title: 'Official Version', isAlbum: true },
    { artist: 'Nitzer Ebb', title: 'That Total Age', isAlbum: true },
    { artist: 'Deutsch Amerikanische Freundschaft', title: 'Alles Ist Gut', isAlbum: true },
    { artist: 'Front 242', title: 'Front By Front', isAlbum: true },
    { artist: 'VNV Nation', title: 'Empires', isAlbum: true },
    { artist: 'And One', title: 'Anguish', isAlbum: true },
    { artist: 'Die Krupps', title: 'Volle Kraft Voraus!', isAlbum: true },
    { artist: 'Front 242', title: 'Tyranny >For You<', isAlbum: true },
    { artist: 'Kode IV', title: 'Insane', isAlbum: true },
    { artist: 'And One', title: 'Bodypop', isAlbum: true },
    { artist: 'Ministry', title: 'The mind is a terrible thing to taste', isAlbum: true },
    { artist: 'KMFDM', title: 'NIHIL', isAlbum: true },
    { artist: 'Front Line Assembly', title: 'Tactical Neural Implant', isAlbum: true },
    { artist: 'GODFLESH', title: 'Streetcleaner', isAlbum: true },
    { artist: 'Nine Inch Nails', title: 'Pretty Hate Machine', isAlbum: true },
    { artist: 'Skinny Puppy', title: 'VIVISect VI', isAlbum: true },
    { artist: 'Einstürzende Neubauten', title: 'Halber Mensch', isAlbum: true },
    { artist: 'Throbbing Gristle', title: '20 Jazz Funk Greats', isAlbum: true },
    { artist: 'Skinny Puppy', title: 'Too Dark Park', isAlbum: true },
    { artist: 'Ministry', title: 'Psalm 69', isAlbum: true },
    { artist: 'KMFDM', title: 'WWIII', isAlbum: true },
    { artist: 'NIN', title: 'The Downward Spiral', isAlbum: true },
    { artist: 'The Synthetic Dream Foundation', title: 'A silvered freeze', isAlbum: false },
    { artist: 'Synthetic Dream Foundation', title: 'Construction of the Underworld', isAlbum: false },
    { artist: 'The Synthetic Dream Foundation', title: 'glittered ripples from the depths', isAlbum: false },
    { artist: 'And One', title: 'Driving with My Darling', isAlbum: false },
    { artist: 'KMFDM', title: 'I (Heart) You', isAlbum: false },
    { artist: 'KMFDM', title: 'Bait & Switch', isAlbum: false },
    { artist: 'KMFDM', title: 'Megalomaniac', isAlbum: false },
    { artist: 'Miss Construction', title: 'Hass Und Liebe', isAlbum: false },
    { artist: 'Miss Construction', title: 'Miss Construction Theme', isAlbum: false },
    { artist: 'Miss Construction', title: 'Headshot', isAlbum: false },
    { artist: 'And One', title: 'Military Fashion Show', isAlbum: false },
    { artist: 'And One', title: 'I Saw Nothing Good so I Left', isAlbum: true },
    { artist: 'Bragolin', title: 'Spot', isAlbum: true },
    { artist: 'Black Magnet', title: 'Megamantra', isAlbum: true },
    { artist: 'In Covert', title: 'Bleak Machinery', isAlbum: true },
    { artist: 'Facs', title: 'Wish Defense', isAlbum: true },
    { artist: 'Floating', title: 'Hesitating Lights', isAlbum: true },
    { artist: 'Bambara', title: 'Birthmarks', isAlbum: true },
    { artist: 'The Gift Is A Curse', title: 'Heir', isAlbum: true },
    { artist: 'Starbenders', title: 'The Beast Goes On', isAlbum: true },
    { artist: 'Ellende', title: 'Zerfall', isAlbum: true },
    { artist: 'Converge', title: 'Love is Not Enough', isAlbum: true },
    { artist: 'Kreator', title: 'Krushers of the World', isAlbum: true },
    { artist: 'MØL', title: 'DREAMCRUSH', isAlbum: true },
    { artist: 'Danko Jones', title: 'Leo Rising', isAlbum: true },
    { artist: 'Tailgunner', title: 'Midnight Blitz', isAlbum: true },
    { artist: 'Bizarrekult', title: 'Alt Som Finnes', isAlbum: true },
    { artist: 'Second Harbour', title: 'Coalesce', isAlbum: true },
    { artist: 'Prehistoria', title: 'Cryptic Halo', isAlbum: true },
    { artist: 'Squeaky Feet', title: 'Overview Effect', isAlbum: true },
    { artist: 'After Forever', title: 'Leaden Legacy', isAlbum: false },
    { artist: 'Flowing Tears', title: 'Merlin', isAlbum: false },
    { artist: 'Rome', title: 'A Legacy of Unrest', isAlbum: false },
    { artist: 'Evereve', title: 'Kolyma', isAlbum: false },
    { artist: 'Thora', title: 'Serpent Heart', isAlbum: false },
    { artist: 'Tribulation', title: 'Sub Rosa in Aeternam', isAlbum: true },
    { artist: 'Unto Others', title: 'Never, Neverland', isAlbum: true },
    { artist: 'Trail of Tears', title: 'Winds of Disdain', isAlbum: true },
    { artist: 'My Dying Bride', title: 'A Mortal Binding', isAlbum: true },
    { artist: 'Swallow the Sun', title: 'Shining', isAlbum: true },
    { artist: 'Rotting Christ', title: 'Pro Xristou', isAlbum: true },
    { artist: 'High Parasite', title: 'Forever We Burn', isAlbum: true },
    { artist: 'Cemetery Skyline', title: 'Nordic Gothic', isAlbum: true },
    { artist: 'Spirewell', title: '...and Fire Whispered unto the Cruel', isAlbum: true },
    { artist: 'The Old Dead Tree', title: 'Second Thoughts', isAlbum: true },
    { artist: 'Tystnaden', title: 'The Black Swan', isAlbum: true },
    { artist: 'Eleanor', title: 'Effigy of the Flowing Tears', isAlbum: true },
    { artist: 'The Foreshadowing', title: 'New Wave Order', isAlbum: true },
    { artist: 'Dark Embrace', title: 'Land of Witches', isAlbum: true },
    { artist: 'Neon Nightmare', title: 'Faded Dream', isAlbum: true },
    { artist: 'Depeche Mode', title: 'Exciter', isAlbum: true },
    { artist: 'Depeche Mode', title: 'Songs Of Faith & Devotion', isAlbum: true },
    { artist: 'Metallica', title: 'Black Album', isAlbum: true },
    { artist: 'The Third and the Mortal', title: 'Tears Laid in Tears', isAlbum: false },
    { artist: 'The Third and the Mortal', title: 'Sorrow EP', isAlbum: false },
    { artist: 'The Gathering', title: 'Mandyllion', isAlbum: true },
    { artist: 'Depeche Mode', title: 'People Are People', isAlbum: false },
    { artist: 'Bauhaus', title: "Bela Lugosi's Dead", isAlbum: false },
    { artist: 'The Sisters of Mercy', title: 'Lucretia My Reflection', isAlbum: false },
    { artist: 'The Cure', title: 'Japanese Whispers', isAlbum: false },
    { artist: 'The Damned', title: 'Love Song', isAlbum: false },
    { artist: 'Siouxsie', title: 'Happy House', isAlbum: false },
    { artist: 'Deutsch Amerikanische Freundschaft', title: 'Der Mussolini', isAlbum: false },
  ];
  
  return entries;
};

const genreMapping: Record<string, Genre[]> = {
  'Sara Noxx': ['Dark Wave', 'Gothic Rock', 'Neue Deutsche Todeskunst', 'Dark Synthpop'],
  'Rotersand': ['Future Pop', 'Electronic Body Music', 'Dark Electro', 'Electro Industrial'],
  'In Strict Confidence': ['Future Pop', 'Electronic Body Music', 'Dark Electro', 'Dark Synthpop'],
  'SONO': ['Dark Synthpop', 'Electronic Body Music', 'Future Pop', 'Dark Electro'],
  'Pink Turns Blue': ['Post Punk', 'Gothic Rock', 'Dark Wave', 'Cold Wave'],
  ':Wumpscut:': ['Aggrotech', 'Dark Electro', 'Harsh EBM', 'Industrial'],
  'Welle: Erdball': ['Electronic Body Music', 'Dark Synthpop', 'Future Pop', 'Industrial'],
  'Iggy Pop': ['Post Punk', 'Gothic Rock', 'Deathrock'],
  'Decoded Feedback': ['Electronic Body Music', 'Dark Electro', 'Future Pop', 'Aggrotech'],
  '8KIDS': ['Neue Deutsche Härte', 'Industrial Metal', 'Electronic Body Music', 'Aggrotech'],
  'Biffy Clyro': ['Post Punk', 'Gothic Rock', 'Dark Metal'],
  'The Cult': ['Gothic Rock', 'Post Punk', 'Dark Metal'],
  'Rob Zombie': ['Industrial Metal', 'Dark Metal', 'Neue Deutsche Härte'],
  'ASP': ['Neue Deutsche Todeskunst', 'Dark Wave', 'Gothic Rock', 'Neoklassik'],
  'New Order': ['Post Punk', 'Dark Wave', 'Dark Synthpop', 'Electronic Body Music'],
  'Pet Shop Boys': ['Dark Synthpop', 'Electronic Body Music', 'Future Pop'],
  'RROYCE': ['Future Pop', 'Dark Synthpop', 'Electronic Body Music', 'Dark Electro'],
  'In Good Faith': ['Future Pop', 'Dark Synthpop', 'Electronic Body Music', 'Electro Industrial'],
  'Inertia': ['Dark Electro', 'Electronic Body Music', 'Electro Industrial', 'Future Pop'],
  'Zweite Jugend': ['Electronic Body Music', 'Dark Synthpop', 'Neue Deutsche Härte'],
  'Crematory': ['Gothic Metal', 'Death Doom', 'Dark Metal', 'Doom Metal'],
  'Bosse': ['Dark Wave', 'Gothic Rock', 'Neue Deutsche Todeskunst'],
  'AnnenMayKantereit': ['Dark Wave', 'Post Punk', 'Gothic Rock'],
  'diorama': ['Future Pop', 'Dark Synthpop', 'Electronic Body Music', 'Dark Electro'],
  'In Mitra Medusa Inri': ['Dark Wave', 'Neoklassik', 'Ethereal Wave', 'Ritual Ambient'],
  'Lakeside X': ['Future Pop', 'Electronic Body Music', 'Dark Electro', 'Dark Synthpop'],
  'Mesh': ['Future Pop', 'Dark Synthpop', 'Electronic Body Music', 'Dark Electro'],
  'Baltes and Zaeyn': ['Darksynth', 'Dark Electro', 'Cybergoth', 'Aggrotech'],
  'Fortification 55': ['Electronic Body Music', 'Dark Electro', 'Future Pop', 'Industrial'],
  'Scheuber': ['Electronic Body Music', 'Future Pop', 'Dark Synthpop', 'Industrial'],
  'Oasis': ['Post Punk', 'Gothic Rock', 'Dark Wave'],
  'T!ANA': ['Dark Electro', 'Electronic Body Music', 'Aggrotech', 'Harsh EBM'],
  'Dorian Black': ['Dark Electro', 'Electronic Body Music', 'Aggrotech', 'Future Pop'],
  'The Halo Trees': ['Dark Wave', 'Post Punk', 'Gothic Rock', 'Ethereal Wave'],
  'Kopetti': ['Dark Electro', 'Electronic Body Music', 'Harsh EBM', 'Aggrotech'],
  'Death Valley Fight Club': ['Aggrotech', 'Harsh EBM', 'Dark Electro', 'Industrial'],
  'Hidden Souls': ['Dark Wave', 'Gothic Rock', 'Post Punk', 'Ethereal Wave'],
  'Mängelexemplar': ['Electronic Body Music', 'Dark Electro', 'Neue Deutsche Härte', 'Industrial'],
  'Twin Noir': ['Dark Wave', 'Dark Synthpop', 'Future Pop', 'Gothic Rock'],
  'Schattenfrequenz': ['Dark Electro', 'Electronic Body Music', 'Aggrotech', 'Industrial'],
  'Beyond Border': ['Electronic Body Music', 'Dark Electro', 'Future Pop', 'Aggrotech'],
  'Projekt JU': ['Dark Electro', 'Electronic Body Music', 'Future Pop', 'Cybergoth'],
  'Lightshifters': ['Dark Electro', 'Electronic Body Music', 'Future Pop', 'Aggrotech'],
  'Flesh Field': ['Aggrotech', 'Dark Electro', 'Harsh EBM', 'Industrial'],
  'Machine Command': ['Electronic Body Music', 'Dark Electro', 'Aggrotech', 'Industrial'],
  'Dawn of Ashes': ['Aggrotech', 'Harsh EBM', 'Dark Electro', 'Death Industrial'],
  'Lorning': ['Dark Wave', 'Future Pop', 'Dark Synthpop', 'Electronic Body Music'],
  'IAMX': ['Dark Wave', 'Dark Synthpop', 'Electronic Body Music', 'Future Pop'],
  'Raf Duran': ['Dark Electro', 'Electronic Body Music', 'Aggrotech', 'Future Pop'],
  'Diorama': ['Future Pop', 'Dark Synthpop', 'Electronic Body Music', 'Dark Electro'],
  'Seelennacht': ['Dark Wave', 'Future Pop', 'Dark Synthpop', 'Electronic Body Music'],
  'Beyond Obsession': ['Dark Electro', 'Electronic Body Music', 'Aggrotech', 'Future Pop'],
  'Look Mum No Computer': ['Dark Synthpop', 'Electronic Body Music', 'Future Pop', 'Cybergoth'],
  'Huir': ['Dark Electro', 'Electronic Body Music', 'Aggrotech', 'Harsh EBM'],
  'Rebel Empire': ['Electronic Body Music', 'Aggrotech', 'Dark Electro', 'Harsh EBM'],
  'SYNTHATTACK': ['Aggrotech', 'Electronic Body Music', 'Dark Electro', 'Harsh EBM'],
  'FREAKY MIND': ['Aggrotech', 'Dark Electro', 'Electronic Body Music', 'Harsh EBM'],
  'BASSZILLA': ['Aggrotech', 'Harsh EBM', 'Dark Electro', 'Cybergoth'],
  'NEUROKLAST': ['Aggrotech', 'Harsh EBM', 'Dark Electro', 'Death Industrial'],
  'DEAD LIGHTS': ['Dark Electro', 'Aggrotech', 'Electronic Body Music', 'Cybergoth'],
  'CIRCUIT PREACHER': ['Aggrotech', 'Electronic Body Music', 'Dark Electro', 'Industrial Metal'],
  'EXTIZE': ['Aggrotech', 'Harsh EBM', 'Dark Electro', 'Cybergoth'],
  'AGNIS': ['Dark Electro', 'Electronic Body Music', 'Aggrotech', 'Future Pop'],
  'HER OWN WORLD': ['Future Pop', 'Dark Synthpop', 'Electronic Body Music', 'Dark Electro'],
  'OMNIMAR': ['Darksynth', 'Dark Electro', 'Electronic Body Music', 'Cybergoth'],
  'BLACKBOOK': ['Electronic Body Music', 'Dark Electro', 'Aggrotech', 'Future Pop'],
  'ANTIBODY': ['Aggrotech', 'Harsh EBM', 'Dark Electro', 'Industrial'],
  'KYUNAA': ['Dark Electro', 'Aggrotech', 'Electronic Body Music', 'Cybergoth'],
  'DANCE MY DARLING': ['Dark Synthpop', 'Future Pop', 'Electronic Body Music', 'Dark Electro'],
  'APNOIE': ['Electronic Body Music', 'Dark Electro', 'Future Pop', 'Industrial'],
  'The Synthetic Dream Foundation': ['Dark Electro', 'Electronic Body Music', 'Electro Industrial', 'Rhythmic Noise'],
  'Informatik': ['Future Pop', 'Dark Synthpop', 'Electronic Body Music', 'Dark Electro'],
  'Autoclav1.1': ['Electronic Body Music', 'Dark Electro', 'Electro Industrial', 'Harsh EBM'],
  'E-Craft': ['Electronic Body Music', 'Dark Electro', 'Aggrotech', 'Future Pop'],
  'Front Line Assembly': ['Electronic Body Music', 'Electro Industrial', 'Dark Electro', 'Industrial'],
  'Gary Numan': ['Dark Synthpop', 'Electronic Body Music', 'Future Pop', 'Industrial'],
  'Hanzel und Gretyl': ['Neue Deutsche Härte', 'Industrial Metal', 'Electronic Body Music', 'Aggrotech'],
  'Comaduster': ['Dark Electro', 'Electro Industrial', 'Electronic Body Music', 'Rhythmic Noise'],
  'Porcelain And The Tramps': ['Dark Electro', 'Electronic Body Music', 'Industrial', 'Aggrotech'],
  'Omnimar': ['Darksynth', 'Dark Electro', 'Electronic Body Music', 'Cybergoth'],
  'Panzer AG': ['Aggrotech', 'Harsh EBM', 'Dark Electro', 'Electronic Body Music'],
  'Necro Facility': ['Aggrotech', 'Harsh EBM', 'Dark Electro', 'Electronic Body Music'],
  'Mind in a Box': ['Future Pop', 'Dark Synthpop', 'Electronic Body Music', 'Dark Electro'],
  'Aslan Faction': ['Electronic Body Music', 'Dark Electro', 'Electro Industrial', 'Industrial'],
  'Stendeck': ['Rhythmic Noise', 'Dark Electro', 'Electro Industrial', 'Electronic Body Music'],
  'AL1CE': ['Dark Electro', 'Electronic Body Music', 'Aggrotech', 'Future Pop'],
  'Lucidstatic': ['Dark Electro', 'Electronic Body Music', 'Aggrotech', 'Harsh EBM'],
  'Zardonic': ['Crossbreed', 'Darkstep', 'Aggrotech', 'Harsh EBM'],
  'Tweaker': ['Industrial', 'Dark Electro', 'Electro Industrial', 'Rhythmic Noise'],
  'Diary Of Dreams': ['Dark Wave', 'Gothic Rock', 'Dark Synthpop', 'Electronic Body Music'],
  'Pleban': ['Dark Electro', 'Electronic Body Music', 'Aggrotech', 'Harsh EBM'],
  'Project Pitchfork': ['Electronic Body Music', 'Dark Electro', 'Future Pop', 'Industrial'],
  'Agonoize': ['Aggrotech', 'Harsh EBM', 'Dark Electro', 'Electronic Body Music'],
  'Totem Obscura': ['Neofolk', 'Ritual Ambient', 'Dark Wave', 'Neoklassik'],
  'Shadowplay': ['Dark Wave', 'Gothic Rock', 'Post Punk', 'Electronic Body Music'],
  'Xylonite Ivy': ['Dark Electro', 'Electronic Body Music', 'Future Pop', 'Dark Synthpop'],
  'Bodanegra': ['Dark Electro', 'Electronic Body Music', 'Aggrotech', 'Dark Synthpop'],
  'NNHMN': ['Cold Wave', 'Post Punk', 'Dark Wave', 'Gothic Rock'],
  'Maman Kusters': ['Electronic Body Music', 'Dark Electro', 'Future Pop', 'Dark Synthpop'],
  'Ministry': ['Industrial Metal', 'Electronic Body Music', 'Industrial', 'Aggrotech'],
  'Skinny Puppy': ['Electro Industrial', 'Electronic Body Music', 'Industrial', 'Aggrotech'],
  'Messa': ['Doom Metal', 'Gothic Metal', 'Death Doom', 'Dark Metal'],
  'Deafheaven': ['Atmospheric Black Metal', 'Dark Metal', 'Post Punk', 'Gothic Metal'],
  'Chat Pile': ['Industrial', 'Dark Metal', 'Post Punk', 'Death Industrial'],
  'Der Weg einer Freiheit': ['Atmospheric Black Metal', 'Dark Metal', 'Pagan Metal', 'Gothic Metal'],
  'Hedonist': ['Doom Metal', 'Death Doom', 'Dark Metal', 'Gothic Metal'],
  'Agriculture': ['Atmospheric Black Metal', 'Dark Metal', 'Post Punk', 'Doom Metal'],
  'Deftones': ['Dark Metal', 'Industrial Metal', 'Post Punk', 'Gothic Metal'],
  'Yellow Eyes': ['Atmospheric Black Metal', 'Dark Metal', 'Pagan Metal', 'Gothic Metal'],
  'Starbynary': ['Dark Synthpop', 'Electronic Body Music', 'Future Pop', 'Darksynth'],
  'Stormbreaker': ['Dark Metal', 'Gothic Metal', 'Symphonic Metal', 'Doom Metal'],
  'Front 242': ['Electronic Body Music', 'Electro Industrial', 'Industrial', 'Dark Electro'],
  'Nitzer Ebb': ['Electronic Body Music', 'Industrial', 'Electro Industrial', 'Aggrotech'],
  'Deutsch Amerikanische Freundschaft': ['Electronic Body Music', 'Industrial', 'Cold Wave', 'Dark Electro'],
  'VNV Nation': ['Future Pop', 'Electronic Body Music', 'Dark Synthpop', 'Dark Electro'],
  'And One': ['Electronic Body Music', 'Dark Synthpop', 'Future Pop', 'Dark Electro'],
  'Die Krupps': ['Electronic Body Music', 'Industrial Metal', 'Neue Deutsche Härte', 'Industrial'],
  'Kode IV': ['Electronic Body Music', 'Dark Electro', 'Aggrotech', 'Industrial'],
  'KMFDM': ['Industrial', 'Industrial Metal', 'Electronic Body Music', 'Aggrotech'],
  'GODFLESH': ['Industrial Metal', 'Doom Metal', 'Industrial', 'Dark Metal'],
  'Nine Inch Nails': ['Industrial', 'Industrial Metal', 'Electronic Body Music', 'Dark Electro'],
  'Einstürzende Neubauten': ['Industrial', 'Death Industrial', 'Dark Wave', 'Electro Industrial'],
  'Throbbing Gristle': ['Industrial', 'Death Industrial', 'Electro Industrial', 'Dark Electro'],
  'NIN': ['Industrial', 'Industrial Metal', 'Electronic Body Music', 'Dark Electro'],
  'Synthetic Dream Foundation': ['Dark Electro', 'Electronic Body Music', 'Electro Industrial', 'Rhythmic Noise'],
  'Miss Construction': ['Aggrotech', 'Harsh EBM', 'Dark Electro', 'Electronic Body Music'],
  'Bragolin': ['Dark Wave', 'Post Punk', 'Gothic Rock', 'Cold Wave'],
  'Black Magnet': ['Industrial', 'Industrial Metal', 'Dark Electro', 'Rhythmic Noise'],
  'In Covert': ['Post Punk', 'Dark Wave', 'Gothic Rock', 'Industrial'],
  'Facs': ['Post Punk', 'Dark Wave', 'Gothic Rock', 'Industrial'],
  'Floating': ['Dark Wave', 'Post Punk', 'Ethereal Wave', 'Gothic Rock'],
  'Bambara': ['Post Punk', 'Dark Wave', 'Gothic Rock', 'Deathrock'],
  'The Gift Is A Curse': ['Dark Metal', 'Industrial Metal', 'Post Punk', 'Doom Metal'],
  'Starbenders': ['Gothic Rock', 'Post Punk', 'Dark Wave', 'Dark Metal'],
  'Ellende': ['Atmospheric Black Metal', 'Dark Metal', 'Doom Metal', 'Gothic Metal'],
  'Converge': ['Dark Metal', 'Industrial Metal', 'Post Punk', 'Gothic Metal'],
  'Kreator': ['Dark Metal', 'Gothic Metal', 'Doom Metal', 'Symphonic Metal'],
  'MØL': ['Atmospheric Black Metal', 'Dark Metal', 'Gothic Metal', 'Post Punk'],
  'Danko Jones': ['Dark Metal', 'Gothic Metal', 'Post Punk', 'Industrial Metal'],
  'Tailgunner': ['Dark Metal', 'Gothic Metal', 'Doom Metal', 'Symphonic Metal'],
  'Bizarrekult': ['Atmospheric Black Metal', 'Dark Metal', 'Pagan Metal', 'Gothic Metal'],
  'Second Harbour': ['Post Punk', 'Dark Wave', 'Gothic Rock', 'Industrial'],
  'Prehistoria': ['Doom Metal', 'Dark Metal', 'Gothic Metal', 'Atmospheric Black Metal'],
  'Squeaky Feet': ['Post Punk', 'Dark Wave', 'Gothic Rock', 'Industrial'],
  'After Forever': ['Symphonic Metal', 'Gothic Metal', 'Dark Metal', 'Doom Metal'],
  'Flowing Tears': ['Gothic Metal', 'Dark Metal', 'Doom Metal', 'Symphonic Metal'],
  'Rome': ['Neofolk', 'Pagan Folk', 'Ritual Ambient', 'Neoklassik'],
  'Evereve': ['Gothic Metal', 'Dark Metal', 'Doom Metal', 'Symphonic Metal'],
  'Thora': ['Gothic Metal', 'Dark Metal', 'Doom Metal', 'Atmospheric Black Metal'],
  'Tribulation': ['Gothic Metal', 'Dark Metal', 'Doom Metal', 'Symphonic Black Metal'],
  'Unto Others': ['Gothic Metal', 'Dark Metal', 'Post Punk', 'Doom Metal'],
  'Trail of Tears': ['Gothic Metal', 'Symphonic Metal', 'Dark Metal', 'Doom Metal'],
  'My Dying Bride': ['Death Doom', 'Gothic Metal', 'Doom Metal', 'Dark Metal'],
  'Swallow the Sun': ['Death Doom', 'Doom Metal', 'Gothic Metal', 'Dark Metal'],
  'Rotting Christ': ['Symphonic Black Metal', 'Dark Metal', 'Pagan Metal', 'Gothic Metal'],
  'High Parasite': ['Gothic Metal', 'Dark Metal', 'Doom Metal', 'Atmospheric Black Metal'],
  'Cemetery Skyline': ['Gothic Metal', 'Doom Metal', 'Dark Metal', 'Death Doom'],
  'Spirewell': ['Atmospheric Black Metal', 'Gothic Metal', 'Dark Metal', 'Doom Metal'],
  'The Old Dead Tree': ['Gothic Metal', 'Doom Metal', 'Dark Metal', 'Death Doom'],
  'Tystnaden': ['Gothic Metal', 'Dark Metal', 'Doom Metal', 'Atmospheric Black Metal'],
  'Eleanor': ['Gothic Metal', 'Death Doom', 'Doom Metal', 'Dark Metal'],
  'The Foreshadowing': ['Doom Metal', 'Gothic Metal', 'Dark Metal', 'Death Doom'],
  'Dark Embrace': ['Gothic Metal', 'Dark Metal', 'Doom Metal', 'Symphonic Metal'],
  'Neon Nightmare': ['Dark Synthpop', 'Darksynth', 'Electronic Body Music', 'Future Pop'],
  'Depeche Mode': ['Dark Synthpop', 'Electronic Body Music', 'Dark Wave', 'Future Pop'],
  'Metallica': ['Dark Metal', 'Gothic Metal', 'Doom Metal', 'Industrial Metal'],
  'The Third and the Mortal': ['Gothic Metal', 'Doom Metal', 'Dark Metal', 'Ethereal Wave'],
  'The Gathering': ['Gothic Metal', 'Doom Metal', 'Dark Metal', 'Ethereal Wave'],
  'Bauhaus': ['Gothic Rock', 'Post Punk', 'Deathrock', 'Dark Wave'],
  'The Sisters of Mercy': ['Gothic Rock', 'Post Punk', 'Dark Wave', 'Deathrock'],
  'The Cure': ['Gothic Rock', 'Post Punk', 'Dark Wave', 'Cold Wave'],
  'The Damned': ['Gothic Rock', 'Post Punk', 'Deathrock', 'Dark Wave'],
  'Siouxsie': ['Gothic Rock', 'Post Punk', 'Dark Wave', 'Deathrock'],
};

export const generateComprehensiveCharts = (): { fanCharts: Track[], expertCharts: Track[], streamingCharts: Track[] } => {
  const entries = parseSongEntries();
  const fanCharts: Track[] = [];
  const expertCharts: Track[] = [];
  const streamingCharts: Track[] = [];

  entries.forEach((entry, index) => {
    const artistKey = entry.artist.includes('feat.') 
      ? entry.artist.split('feat.')[0].trim() 
      : entry.artist.includes(' x ') 
        ? entry.artist.split(' x ')[0].trim()
        : entry.artist;
    
    const genres = genreMapping[artistKey] || ['Dark Wave', 'Gothic Rock', 'Electronic Body Music', 'Dark Electro'];
    
    const baseTrack = {
      artist: entry.artist,
      title: entry.title,
      genres: genres.slice(0, Math.min(5, genres.length)) as Genre[],
      album: entry.isAlbum ? entry.title : undefined,
      votes: Math.floor(Math.random() * 500) + 50,
    };

    const fanScore = Math.random() * 100;
    const expertScore = Math.random() * 100;
    const streamingScore = Math.random() * 100;

    if (index % 3 === 0) {
      fanCharts.push({
        ...baseTrack,
        id: `fan-${index}`,
        rank: fanCharts.length + 1,
        chartType: 'fan',
        fanScore,
        expertScore,
        streamingScore,
        movement: Math.floor(Math.random() * 10) - 5,
      });
    }
    
    if (index % 3 === 1) {
      expertCharts.push({
        ...baseTrack,
        id: `expert-${index}`,
        rank: expertCharts.length + 1,
        chartType: 'expert',
        fanScore,
        expertScore,
        streamingScore,
        movement: Math.floor(Math.random() * 10) - 5,
      });
    }
    
    if (index % 3 === 2) {
      streamingCharts.push({
        ...baseTrack,
        id: `streaming-${index}`,
        rank: streamingCharts.length + 1,
        chartType: 'streaming',
        fanScore,
        expertScore,
        streamingScore,
        movement: Math.floor(Math.random() * 10) - 5,
      });
    }
  });

  return { fanCharts, expertCharts, streamingCharts };
};
