import { Track } from '@/types';

export const mockFanCharts: Track[] = [
  {
    id: 'fan-1',
    rank: 1,
    artist: 'Heilung',
    title: 'Anoana',
    genres: ['Dark Wave', 'Industrial'],
    movement: 2,
    previousRank: 3,
    chartType: 'fan',
    fanScore: 98,
    expertScore: 85,
    streamingScore: 72,
    albumArt: 'https://picsum.photos/seed/heilung/400/400',
    spotifyUri: 'spotify:track:3xXBsjrbG1LDIAKigJfA1w',
    votes: 147,
    weeksInChart: 8,
    album: 'Futha',
    releaseDate: '2019-06-28',
    label: 'Season of Mist',
    appleMusicUrl: 'https://music.apple.com/album/anoana',
    amazonMusicUrl: 'https://music.amazon.com/albums/anoana',
    youtubeUrl: 'https://www.youtube.com/watch?v=SVbc_Fwbt50'
  },
  {
    id: 'fan-2',
    rank: 2,
    artist: 'Wardruna',
    title: 'Helvegen',
    genres: ['Gothic Rock', 'Dark Wave'],
    movement: -1,
    previousRank: 1,
    chartType: 'fan',
    fanScore: 95,
    expertScore: 92,
    streamingScore: 88,
    albumArt: 'https://picsum.photos/seed/wardruna/400/400',
    spotifyUri: 'spotify:track:0FutrWIUM5Mg3434asiwkp',
    votes: 132,
    weeksInChart: 12,
    album: 'Runaljod - Yggdrasil',
    releaseDate: '2013-03-15',
    label: 'Indie Recordings',
    appleMusicUrl: 'https://music.apple.com/album/helvegen',
    amazonMusicUrl: 'https://music.amazon.com/albums/helvegen',
    youtubeUrl: 'https://www.youtube.com/watch?v=DD65K4VR6Mk'
  },
  {
    id: 'fan-3',
    rank: 3,
    artist: 'Perturbator',
    title: 'Neo Tokyo',
    genres: ['Darksynth', 'Industrial'],
    movement: 0,
    previousRank: 3,
    chartType: 'fan',
    fanScore: 93,
    expertScore: 78,
    streamingScore: 65,
    albumArt: 'https://picsum.photos/seed/perturbator/400/400',
    spotifyUri: 'spotify:track:3h4CwqQnwhPXlJNPKh4feQ',
    votes: 98,
    weeksInChart: 5,
    album: 'Dangerous Days',
    releaseDate: '2014-05-05',
    label: 'Blood Music',
    appleMusicUrl: 'https://music.apple.com/album/neo-tokyo',
    amazonMusicUrl: 'https://music.amazon.com/albums/neo-tokyo',
    youtubeUrl: 'https://www.youtube.com/watch?v=PrJUSps__fU'
  },
  {
    id: 'fan-4',
    rank: 4,
    artist: 'Sisters of Mercy',
    title: 'Temple of Love',
    genres: ['Gothic Rock'],
    movement: 3,
    previousRank: 7,
    chartType: 'fan',
    fanScore: 91,
    expertScore: 88,
    streamingScore: 82,
    albumArt: 'https://picsum.photos/seed/sisters/400/400',
    spotifyUri: 'spotify:track:1TfqLAPs4K3s2rJMoCokcS',
    votes: 89,
    weeksInChart: 3,
    album: 'Some Girls Wander by Mistake',
    releaseDate: '1992-05-18',
    label: 'Merciful Release',
    appleMusicUrl: 'https://music.apple.com/album/temple-of-love',
    amazonMusicUrl: 'https://music.amazon.com/albums/temple-of-love',
    youtubeUrl: 'https://www.youtube.com/watch?v=Fa0b2Kd2xhU'
  },
  {
    id: 'fan-5',
    rank: 5,
    artist: 'Type O Negative',
    title: 'Black No. 1',
    genres: ['Gothic Rock', 'Doom Metal'],
    movement: -2,
    previousRank: 3,
    chartType: 'fan',
    fanScore: 89,
    expertScore: 90,
    streamingScore: 79,
    albumArt: 'https://picsum.photos/seed/typeo/400/400',
    spotifyUri: 'spotify:track:7qjCVexNgbYNH0qvMYvkxg',
    votes: 76,
    weeksInChart: 15,
    album: 'Bloody Kisses',
    releaseDate: '1993-09-17',
    label: 'Roadrunner Records',
    appleMusicUrl: 'https://music.apple.com/album/black-no-1',
    amazonMusicUrl: 'https://music.amazon.com/albums/black-no-1',
    youtubeUrl: 'https://www.youtube.com/watch?v=vFwYJYl5GUQ'
  }
];

export const mockExpertCharts: Track[] = [
  {
    id: 'expert-1',
    rank: 1,
    artist: 'Neurosis',
    title: 'Through Silver in Blood',
    genres: ['Doom Metal', 'Industrial'],
    movement: 0,
    previousRank: 1,
    chartType: 'expert',
    fanScore: 78,
    expertScore: 99,
    streamingScore: 45,
    albumArt: 'https://picsum.photos/seed/neurosis/400/400',
    spotifyUri: 'spotify:track:4RVnAU35WRWra6OZ3CbbwA',
    votes: 203,
    weeksInChart: 6
  },
  {
    id: 'expert-2',
    rank: 2,
    artist: 'Ulver',
    title: 'Bergtatt',
    genres: ['Atmospheric Black Metal', 'Dark Wave'],
    movement: 1,
    previousRank: 3,
    chartType: 'expert',
    fanScore: 82,
    expertScore: 97,
    streamingScore: 52,
    albumArt: 'https://picsum.photos/seed/ulver/400/400',
    spotifyUri: 'spotify:track:2ZWlPOoWh0626oTaHrnl2a',
    votes: 187,
    weeksInChart: 9
  },
  {
    id: 'expert-3',
    rank: 3,
    artist: 'Dead Can Dance',
    title: 'The Host of Seraphim',
    genres: ['Gothic Rock', 'Dark Wave'],
    movement: -1,
    previousRank: 2,
    chartType: 'expert',
    fanScore: 85,
    expertScore: 96,
    streamingScore: 68,
    albumArt: 'https://picsum.photos/seed/deadcandance/400/400',
    spotifyUri: 'spotify:track:5uLrWiFmE4llLULJ4j3PcW',
    votes: 164,
    weeksInChart: 11
  },
  {
    id: 'expert-4',
    rank: 4,
    artist: 'Godflesh',
    title: 'Streetcleaner',
    genres: ['Industrial', 'Doom Metal'],
    movement: 2,
    previousRank: 6,
    chartType: 'expert',
    fanScore: 71,
    expertScore: 95,
    streamingScore: 38,
    albumArt: 'https://picsum.photos/seed/godflesh/400/400',
    spotifyUri: 'spotify:track:3KjYS5fvP0ThOYbTwW0TZD',
    votes: 141,
    weeksInChart: 4
  },
  {
    id: 'expert-5',
    rank: 5,
    artist: 'Swans',
    title: 'The Seer',
    genres: ['Industrial'],
    movement: 0,
    previousRank: 5,
    chartType: 'expert',
    fanScore: 76,
    expertScore: 94,
    streamingScore: 41,
    albumArt: 'https://picsum.photos/seed/swans/400/400',
    spotifyUri: 'spotify:track:2yvmvDHYpj6l1WkLcxrM6B',
    votes: 119,
    weeksInChart: 7
  }
];

export const mockStreamingCharts: Track[] = [
  {
    id: 'streaming-1',
    rank: 1,
    artist: 'Ghost',
    title: 'Square Hammer',
    genres: ['Gothic Rock'],
    movement: 0,
    previousRank: 1,
    chartType: 'streaming',
    fanScore: 88,
    expertScore: 82,
    streamingScore: 98,
    albumArt: 'https://picsum.photos/seed/ghost/400/400',
    spotifyUri: 'spotify:track:14HbJBOp8OTzeg5wIRWNOL',
    votes: 256,
    weeksInChart: 20
  },
  {
    id: 'streaming-2',
    rank: 2,
    artist: 'Carpenter Brut',
    title: 'Turbo Killer',
    genres: ['Darksynth', 'Industrial'],
    movement: 1,
    previousRank: 3,
    chartType: 'streaming',
    fanScore: 91,
    expertScore: 79,
    streamingScore: 95,
    albumArt: 'https://picsum.photos/seed/carpenter/400/400',
    spotifyUri: 'spotify:track:70DdGHW8NsKwTjxBQkW2gq',
    votes: 221,
    weeksInChart: 14
  },
  {
    id: 'streaming-3',
    rank: 3,
    artist: 'Depeche Mode',
    title: 'Enjoy the Silence',
    genres: ['Dark Synthpop', 'Dark Wave'],
    movement: -1,
    previousRank: 2,
    chartType: 'streaming',
    fanScore: 93,
    expertScore: 87,
    streamingScore: 94,
    albumArt: 'https://picsum.photos/seed/depeche/400/400',
    spotifyUri: 'spotify:track:07WXiBgLNo9JuG7qpsvvKg',
    votes: 198,
    weeksInChart: 18
  },
  {
    id: 'streaming-4',
    rank: 4,
    artist: 'Nine Inch Nails',
    title: 'Hurt',
    genres: ['Industrial'],
    movement: 2,
    previousRank: 6,
    chartType: 'streaming',
    fanScore: 89,
    expertScore: 91,
    streamingScore: 92,
    albumArt: 'https://picsum.photos/seed/nin/400/400',
    spotifyUri: 'spotify:track:5T08Ce6VZOi3sQx5kOPLus',
    votes: 183,
    weeksInChart: 2
  },
  {
    id: 'streaming-5',
    rank: 5,
    artist: 'The Cure',
    title: 'A Forest',
    genres: ['Gothic Rock', 'Dark Wave'],
    movement: -1,
    previousRank: 4,
    chartType: 'streaming',
    fanScore: 92,
    expertScore: 88,
    streamingScore: 91,
    albumArt: 'https://picsum.photos/seed/cure/400/400',
    spotifyUri: 'spotify:track:1Qhbi2hK9DPqcJGNp7bVag',
    votes: 167,
    weeksInChart: 10
  }
];
