import { createContext, useContext, ReactNode } from 'react';
import { useKV } from '@github/spark/hooks';

type Language = 'en' | 'de';

type TranslationKey = string;
type Translations = Record<TranslationKey, string>;

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Translations> = {
  en: {
    'nav.home': 'Home',
    'nav.voting': 'Voting',
    'nav.history': 'History',
    'nav.custom': 'Custom Charts',
    'nav.profile': 'Profile',
    'nav.about': 'About',
    
    'pillar.overview': 'Overview',
    'pillar.fan': 'Fan Charts',
    'pillar.expert': 'Expert Charts',
    'pillar.streaming': 'Streaming Charts',
    
    'genre.overall': 'Overall',
    'genre.gothic': 'Gothic',
    'genre.metal': 'Metal',
    'genre.darkelectro': 'Dark Electro',
    'genre.crossover': 'Crossover',
    
    'subgenre.Gothic Rock': 'Gothic Rock',
    'subgenre.Dark Wave': 'Dark Wave',
    'subgenre.Post Punk': 'Post Punk',
    'subgenre.Deathrock': 'Deathrock',
    'subgenre.Cold Wave': 'Cold Wave',
    'subgenre.Ethereal Wave': 'Ethereal Wave',
    'subgenre.Neoklassik': 'Neoclassical',
    'subgenre.Neue Deutsche Todeskunst': 'Neue Deutsche Todeskunst',
    'subgenre.Batcave': 'Batcave',
    'subgenre.Neofolk': 'Neofolk',
    'subgenre.Pagan Folk': 'Pagan Folk',
    'subgenre.Nordic Folk': 'Nordic Folk',
    'subgenre.Ritual Ambient': 'Ritual Ambient',
    'subgenre.Gothic Metal': 'Gothic Metal',
    'subgenre.Dark Metal': 'Dark Metal',
    'subgenre.Symphonic Metal': 'Symphonic Metal',
    'subgenre.Doom Metal': 'Doom Metal',
    'subgenre.Symphonic Black Metal': 'Symphonic Black Metal',
    'subgenre.Atmospheric Black Metal': 'Atmospheric Black Metal',
    'subgenre.Death Doom': 'Death Doom',
    'subgenre.Pagan Metal': 'Pagan Metal',
    'subgenre.Electronic Body Music': 'Electronic Body Music',
    'subgenre.Dark Electro': 'Dark Electro',
    'subgenre.Electro Industrial': 'Electro Industrial',
    'subgenre.Aggrotech': 'Aggrotech',
    'subgenre.Future Pop': 'Future Pop',
    'subgenre.Industrial': 'Industrial',
    'subgenre.Rhythmic Noise': 'Rhythmic Noise',
    'subgenre.Dark Synthpop': 'Dark Synthpop',
    'subgenre.Harsh EBM': 'Harsh EBM',
    'subgenre.Industrial Metal': 'Industrial Metal',
    'subgenre.Neue Deutsche Härte': 'Neue Deutsche Härte',
    'subgenre.Mittelalter Rock': 'Medieval Rock',
    'subgenre.Darksynth': 'Darksynth',
    'subgenre.Cybergoth': 'Cybergoth',
    'subgenre.Death Industrial': 'Death Industrial',
    'subgenre.Folk Metal': 'Folk Metal',
    'subgenre.Dark Techno': 'Dark Techno',
    'subgenre.Industrial Techno': 'Industrial Techno',
    'subgenre.Darkstep': 'Darkstep',
    'subgenre.Crossbreed': 'Crossbreed',
    'subgenre.Techstep': 'Techstep',
    'subgenre.Neurofunk': 'Neurofunk',
    
    'chart.fanCharts': 'Fan Charts',
    'chart.expertCharts': 'Expert Charts',
    'chart.streamingCharts': 'Streaming Charts',
    'chart.overallCharts': 'Overall Charts',
    'chart.top3': 'Top 3',
    'chart.position': 'Position',
    
    'track.artist': 'Artist',
    'track.title': 'Title',
    'track.album': 'Album',
    'track.releaseDate': 'Release Date',
    'track.genres': 'Genres',
    'track.votes': 'Votes',
    'track.streams': 'Streams',
    'track.playOn': 'Play on',
    'track.details': 'Track Details',
    'track.appearsIn': 'Appears in Charts',
    'track.noChartPositions': 'No chart positions',
    
    'player.nowPlaying': 'Now Playing',
    'player.previous': 'Previous',
    'player.next': 'Next',
    'player.noTrack': 'No track selected',
    
    'voting.title': 'Voting Area',
    'voting.description': 'Use quadratic voting to support your favorite tracks',
    'voting.search': 'Search tracks or artists...',
    'voting.filterGenres': 'Filter by Genre',
    'voting.clearFilters': 'Clear Filters',
    'voting.vote': 'Vote',
    'voting.voted': 'Voted',
    'voting.votesRemaining': 'votes remaining',
    'voting.allVotesUsed': 'All votes used',
    'voting.resetIn': 'Reset in',
    'voting.hours': 'hours',
    'voting.minutes': 'minutes',
    'voting.creditsRemaining': 'Credits Remaining',
    'voting.totalCostSpent': 'Total Cost Spent',
    'voting.daysUntilCharts': 'Days Until Charts',
    'voting.quadraticVoting': 'Quadratic Voting',
    'voting.quadraticInfo': 'You have 150 credits to allocate\n• Cost = credits²  (1 credit = 1 cost, 5 credits = 25 cost)\n• Allocate credits across multiple tracks\n• Charts publish weekly every Monday\n• Credits reset after each publication\n• No downvoting - only positive support',
    'voting.rank': 'Rank',
    'voting.credits': 'Credits',
    'voting.cost': 'Cost',
    'voting.allocated': 'You allocated {credits} credits to this track',
    'voting.totalVotes': 'Total Votes',
    'voting.noTracksFound': 'No tracks found matching your filters',
    'voting.loginRequired': 'Please log in to vote',
    'voting.notEnoughCredits': 'Not enough credits! You need {needed} but only have {remaining} remaining.',
    'voting.successAllocated': 'Allocated {credits} credits (cost: {cost})',
    
    'custom.title': 'Custom Charts',
    'custom.description': 'Create your own personalized charts',
    'custom.createChart': 'Create Chart',
    'custom.chartName': 'Chart Name',
    'custom.selectTracks': 'Select Tracks',
    'custom.selectGenres': '{count} selected',
    'custom.save': 'Save',
    'custom.saveChanges': 'Save Changes',
    'custom.cancel': 'Cancel',
    'custom.delete': 'Delete',
    'custom.edit': 'Edit',
    'custom.view': 'View',
    'custom.noCharts': 'No Custom Charts Yet',
    'custom.createFirst': 'Create your first custom chart by selecting genres and weights',
    'custom.createNewChart': 'Create New Chart',
    'custom.editChart': 'Edit Chart',
    'custom.visibility': 'Visibility',
    'custom.private': 'Private',
    'custom.public': 'Public',
    'custom.chartWeights': 'Chart Weights',
    'custom.fanWeight': 'Fan Charts',
    'custom.expertWeight': 'Expert Charts',
    'custom.streamingWeight': 'Streaming Charts',
    'custom.chartResults': 'Chart Results ({count} tracks)',
    'custom.noMatchingTracks': 'No Matching Tracks',
    'custom.adjustFilters': 'Try adjusting your genre filters',
    'custom.genres': '{count} Genres',
    'custom.genre': '{count} Genre',
    
    'trackDetail.currentPosition': 'Current Chart Position',
    'trackDetail.allPositions': 'All Chart Positions',
    'trackDetail.allPositionsInfo': 'Click to navigate to any chart where this track appears',
    'trackDetail.positionInfo': 'Position in the current chart view',
    'trackDetail.currentVotes': 'Current Votes',
    'trackDetail.album': 'Album',
    'trackDetail.releaseDate': 'Release Date',
    'trackDetail.label': 'Label',
    'trackDetail.genres': 'Genres',
    'trackDetail.trackPreview': 'Track Preview',
    'trackDetail.listenOn': 'Listen On',
    'trackDetail.voteUp': 'Vote Up',
    'trackDetail.voteDown': 'Vote Down',
    'trackDetail.increasePosition': 'Increase this track\'s chart position',
    'trackDetail.decreasePosition': 'Decrease this track\'s chart position',
    
    'history.title': 'Chart History',
    'history.description': 'View historical chart positions',
    'history.selectTrack': 'Select a track',
    'history.week': 'Week',
    'history.noData': 'No historical data available',
    
    'profile.title': 'Profile',
    'profile.signIn': 'Sign In to Dark Charts',
    'profile.signInDescription': 'Access your profile, vote for artists, and create custom charts',
    'profile.continueSpotify': 'Continue with Spotify',
    'profile.continueApple': 'Continue with Apple Music',
    'profile.demoAccount': 'Demo Account',
    'profile.or': 'Or',
    'profile.fan': 'Fan',
    'profile.edit': 'Edit',
    'profile.signOut': 'Sign Out',
    'profile.save': 'Save',
    'profile.noBio': 'No biography yet. Click Edit to add one.',
    'profile.bioPlaceholder': 'Tell us about yourself...',
    'profile.votingCredits': 'Voting Credits',
    'profile.availableForVoting': 'Available for voting',
    'profile.votingHistory': 'Voting History',
    'profile.totalVotesCast': 'Total votes cast',
    'profile.favorites': 'Favorites',
    'profile.savedTracks': 'Saved tracks',
    'profile.earnedBadges': 'Earned Badges',
    'profile.username': 'Username',
    'profile.email': 'Email',
    'profile.memberSince': 'Member since',
    'profile.totalVotes': 'Total Votes',
    'profile.customCharts': 'Custom Charts',
    'profile.settings': 'Settings',
    'profile.language': 'Language',
    'profile.saveChanges': 'Save Changes',
    'profile.profileType': 'Profile type',
    'profile.comingSoon': 'Full profile management for Band, DJ, and Label accounts coming soon.',
    
    'about.title': 'About Dark Charts',
    'about.description': 'Independent music charts for Metal & Gothic scene',
    'about.mission': 'Our Mission',
    'about.missionText': 'Independent music charts for the Heavy Metal, Gothic, Dark Wave, and EBM scene. Fair, transparent, and free from pay-to-win mechanics.',
    'about.noPayToPlay': 'No Pay-To-Play',
    'about.noPayToPlayText': 'Artists don\'t pay to be ranked. Rankings are determined solely by authentic fan votes, expert reviews, and streaming engagement.',
    'about.howItWorks': 'How Voting Works',
    'about.fanCharts': 'Fan Charts',
    'about.fanChartsText': 'Community-driven rankings powered by quadratic voting. Each authenticated user receives monthly vote credits to support their favorite artists.',
    'about.expertCharts': 'Expert Charts',
    'about.expertChartsText': 'Curated by DJs, producers, and music journalists using bayesian ranking algorithms. Expert reputation scores ensure quality evaluations.',
    'about.streamingCharts': 'Streaming Charts',
    'about.streamingChartsText': 'Normalized streaming data from Spotify and YouTube, weighted by listener loyalty rather than raw play counts.',
    'about.principles': 'Principles',
    'about.principle1': 'No pay-to-play mechanisms',
    'about.principle2': 'Community-driven rankings',
    'about.principle3': 'Transparent methodology',
    'about.principle4': 'Scene-focused curation',
    'about.principle5': 'Protection against manipulation',
    'about.builtFor': 'Built for fans, by fans. Supporting underground artists through fair representation and authentic community engagement.',
    
    'footer.tagline': 'Independent music charts for Metal & Gothic scene. Fair, transparent, and free from pay-to-win mechanics.',
    'footer.underground': 'Underground Never Dies',
    
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.close': 'Close',
    'common.back': 'Back',
    'common.viewDetails': 'View Details',
    'common.genres': 'Genres',
    'common.all': 'All',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.ascending': 'Ascending',
    'common.descending': 'Descending',
    
    'header.subtitle': 'Metal • Gothic • Alternative • Dark Electro',
    
    'admin.title': 'Artist Management',
    'admin.subtitle': 'Manage artists and sync releases',
    'admin.addArtist': 'Add Artist',
    'admin.editArtist': 'Edit Artist',
    'admin.sync': 'Sync',
    'admin.syncAll': 'Sync All',
    'admin.delete': 'Delete',
    'admin.edit': 'Edit',
    'admin.viewReleases': 'View Releases',
    'admin.releases': 'Releases',
    'admin.tracks': 'Tracks',
    'admin.nextSync': 'Next sync',
    'admin.releasesFor': 'Releases for',
    'admin.status.syncing': 'Syncing',
    'admin.status.success': 'Success',
    'admin.status.error': 'Error',
    'admin.form.name': 'Artist Name',
    'admin.form.spotifyId': 'Spotify Artist ID',
    'admin.form.genres': 'Genres',
    'admin.form.genresHelp': 'Comma-separated list',
    'admin.form.artwork': 'Artwork URL',
    'admin.form.bio': 'Biography',
    'admin.form.save': 'Save',
    'admin.form.cancel': 'Cancel',
    'admin.confirm.deleteArtist': 'Are you sure you want to delete this artist and all releases?',
    'admin.confirm.syncAll': 'Are you sure you want to sync all artists? This may take a while.',
    'admin.success.artistCreated': 'Artist created successfully',
    'admin.success.artistUpdated': 'Artist updated successfully',
    'admin.success.artistDeleted': 'Artist deleted successfully',
    'admin.success.syncCompleted': 'Sync completed successfully',
    'admin.success.syncAllCompleted': 'All artists synced successfully',
    'admin.error.loadArtists': 'Failed to load artists',
    'admin.error.loadReleases': 'Failed to load releases',
    'admin.error.createArtist': 'Failed to create artist',
    'admin.error.updateArtist': 'Failed to update artist',
    'admin.error.deleteArtist': 'Failed to delete artist',
    'admin.error.syncFailed': 'Sync failed',
    'admin.error.syncAllFailed': 'Sync all failed',
    'admin.info.syncStarted': 'Sync started',
    'admin.info.syncAllStarted': 'Syncing all artists...',
    'nav.admin': 'Admin',
  },
  de: {
    'nav.home': 'Startseite',
    'nav.voting': 'Abstimmen',
    'nav.history': 'Verlauf',
    'nav.custom': 'Eigene Charts',
    'nav.profile': 'Profil',
    'nav.about': 'Über uns',
    
    'pillar.overview': 'Übersicht',
    'pillar.fan': 'Fan-Charts',
    'pillar.expert': 'Experten-Charts',
    'pillar.streaming': 'Streaming-Charts',
    
    'genre.overall': 'Gesamt',
    'genre.gothic': 'Gothic',
    'genre.metal': 'Metal',
    'genre.darkelectro': 'Dark Electro',
    'genre.crossover': 'Crossover',
    
    'subgenre.Gothic Rock': 'Gothic Rock',
    'subgenre.Dark Wave': 'Dark Wave',
    'subgenre.Post Punk': 'Post Punk',
    'subgenre.Deathrock': 'Deathrock',
    'subgenre.Cold Wave': 'Cold Wave',
    'subgenre.Ethereal Wave': 'Ethereal Wave',
    'subgenre.Neoklassik': 'Neoklassik',
    'subgenre.Neue Deutsche Todeskunst': 'Neue Deutsche Todeskunst',
    'subgenre.Batcave': 'Batcave',
    'subgenre.Neofolk': 'Neofolk',
    'subgenre.Pagan Folk': 'Pagan Folk',
    'subgenre.Nordic Folk': 'Nordic Folk',
    'subgenre.Ritual Ambient': 'Ritual Ambient',
    'subgenre.Gothic Metal': 'Gothic Metal',
    'subgenre.Dark Metal': 'Dark Metal',
    'subgenre.Symphonic Metal': 'Symphonic Metal',
    'subgenre.Doom Metal': 'Doom Metal',
    'subgenre.Symphonic Black Metal': 'Symphonic Black Metal',
    'subgenre.Atmospheric Black Metal': 'Atmospheric Black Metal',
    'subgenre.Death Doom': 'Death Doom',
    'subgenre.Pagan Metal': 'Pagan Metal',
    'subgenre.Electronic Body Music': 'Electronic Body Music',
    'subgenre.Dark Electro': 'Dark Electro',
    'subgenre.Electro Industrial': 'Electro Industrial',
    'subgenre.Aggrotech': 'Aggrotech',
    'subgenre.Future Pop': 'Future Pop',
    'subgenre.Industrial': 'Industrial',
    'subgenre.Rhythmic Noise': 'Rhythmic Noise',
    'subgenre.Dark Synthpop': 'Dark Synthpop',
    'subgenre.Harsh EBM': 'Harsh EBM',
    'subgenre.Industrial Metal': 'Industrial Metal',
    'subgenre.Neue Deutsche Härte': 'Neue Deutsche Härte',
    'subgenre.Mittelalter Rock': 'Mittelalter Rock',
    'subgenre.Darksynth': 'Darksynth',
    'subgenre.Cybergoth': 'Cybergoth',
    'subgenre.Death Industrial': 'Death Industrial',
    'subgenre.Folk Metal': 'Folk Metal',
    'subgenre.Dark Techno': 'Dark Techno',
    'subgenre.Industrial Techno': 'Industrial Techno',
    'subgenre.Darkstep': 'Darkstep',
    'subgenre.Crossbreed': 'Crossbreed',
    'subgenre.Techstep': 'Techstep',
    'subgenre.Neurofunk': 'Neurofunk',
    
    'chart.fanCharts': 'Fan-Charts',
    'chart.expertCharts': 'Experten-Charts',
    'chart.streamingCharts': 'Streaming-Charts',
    'chart.overallCharts': 'Gesamt-Charts',
    'chart.top3': 'Top 3',
    'chart.position': 'Position',
    
    'track.artist': 'Künstler',
    'track.title': 'Titel',
    'track.album': 'Album',
    'track.releaseDate': 'Veröffentlichungsdatum',
    'track.genres': 'Genres',
    'track.votes': 'Stimmen',
    'track.streams': 'Streams',
    'track.playOn': 'Abspielen auf',
    'track.details': 'Track-Details',
    'track.appearsIn': 'Erscheint in Charts',
    'track.noChartPositions': 'Keine Chart-Positionen',
    
    'player.nowPlaying': 'Läuft gerade',
    'player.previous': 'Zurück',
    'player.next': 'Weiter',
    'player.noTrack': 'Kein Track ausgewählt',
    
    'voting.title': 'Voting-Bereich',
    'voting.description': 'Nutze quadratisches Voting um deine Lieblings-Tracks zu unterstützen',
    'voting.search': 'Tracks oder Künstler durchsuchen...',
    'voting.filterGenres': 'Nach Genre filtern',
    'voting.clearFilters': 'Filter löschen',
    'voting.vote': 'Abstimmen',
    'voting.voted': 'Abgestimmt',
    'voting.votesRemaining': 'Stimmen übrig',
    'voting.allVotesUsed': 'Alle Stimmen verbraucht',
    'voting.resetIn': 'Zurücksetzen in',
    'voting.hours': 'Stunden',
    'voting.minutes': 'Minuten',
    'voting.creditsRemaining': 'Verbleibende Credits',
    'voting.totalCostSpent': 'Gesamtkosten',
    'voting.daysUntilCharts': 'Tage bis Charts',
    'voting.quadraticVoting': 'Quadratisches Voting',
    'voting.quadraticInfo': 'Du hast 150 Credits zum Verteilen\n• Kosten = Credits²  (1 Credit = 1 Kosten, 5 Credits = 25 Kosten)\n• Verteile Credits auf mehrere Tracks\n• Charts werden wöchentlich jeden Montag veröffentlicht\n• Credits werden nach jeder Veröffentlichung zurückgesetzt\n• Kein Downvoting - nur positive Unterstützung',
    'voting.rank': 'Rang',
    'voting.credits': 'Credits',
    'voting.cost': 'Kosten',
    'voting.allocated': 'Du hast {credits} Credits für diesen Track vergeben',
    'voting.totalVotes': 'Gesamtstimmen',
    'voting.noTracksFound': 'Keine Tracks gefunden, die deinen Filtern entsprechen',
    'voting.loginRequired': 'Bitte melde dich an, um abzustimmen',
    'voting.notEnoughCredits': 'Nicht genug Credits! Du benötigst {needed}, hast aber nur {remaining} übrig.',
    'voting.successAllocated': '{credits} Credits vergeben (Kosten: {cost})',
    
    'custom.title': 'Eigene Charts',
    'custom.description': 'Erstelle deine eigenen personalisierten Charts',
    'custom.createChart': 'Chart erstellen',
    'custom.chartName': 'Chart-Name',
    'custom.selectTracks': 'Tracks auswählen',
    'custom.selectGenres': '{count} ausgewählt',
    'custom.save': 'Speichern',
    'custom.saveChanges': 'Änderungen speichern',
    'custom.cancel': 'Abbrechen',
    'custom.delete': 'Löschen',
    'custom.edit': 'Bearbeiten',
    'custom.view': 'Ansehen',
    'custom.noCharts': 'Noch keine eigenen Charts',
    'custom.createFirst': 'Erstelle deine erste eigene Chart, indem du Genres und Gewichte auswählst',
    'custom.createNewChart': 'Neue Chart erstellen',
    'custom.editChart': 'Chart bearbeiten',
    'custom.visibility': 'Sichtbarkeit',
    'custom.private': 'Privat',
    'custom.public': 'Öffentlich',
    'custom.chartWeights': 'Chart-Gewichtungen',
    'custom.fanWeight': 'Fan-Charts',
    'custom.expertWeight': 'Experten-Charts',
    'custom.streamingWeight': 'Streaming-Charts',
    'custom.chartResults': 'Chart-Ergebnisse ({count} Tracks)',
    'custom.noMatchingTracks': 'Keine passenden Tracks',
    'custom.adjustFilters': 'Versuche deine Genre-Filter anzupassen',
    'custom.genres': '{count} Genres',
    'custom.genre': '{count} Genre',
    
    'trackDetail.currentPosition': 'Aktuelle Chart-Position',
    'trackDetail.allPositions': 'Alle Chart-Positionen',
    'trackDetail.allPositionsInfo': 'Klicke um zu einer Chart zu navigieren, in der dieser Track erscheint',
    'trackDetail.positionInfo': 'Position in der aktuellen Chart-Ansicht',
    'trackDetail.currentVotes': 'Aktuelle Stimmen',
    'trackDetail.album': 'Album',
    'trackDetail.releaseDate': 'Veröffentlichungsdatum',
    'trackDetail.label': 'Label',
    'trackDetail.genres': 'Genres',
    'trackDetail.trackPreview': 'Track-Vorschau',
    'trackDetail.listenOn': 'Anhören auf',
    'trackDetail.voteUp': 'Hochstimmen',
    'trackDetail.voteDown': 'Runterstimmen',
    'trackDetail.increasePosition': 'Erhöhe die Chart-Position dieses Tracks',
    'trackDetail.decreasePosition': 'Senke die Chart-Position dieses Tracks',
    
    'profile.signIn': 'Bei Dark Charts anmelden',
    'profile.signInDescription': 'Greife auf dein Profil zu, stimme für Künstler ab und erstelle eigene Charts',
    'profile.continueSpotify': 'Mit Spotify fortfahren',
    'profile.continueApple': 'Mit Apple Music fortfahren',
    'profile.demoAccount': 'Demo-Account',
    'profile.or': 'Oder',
    'profile.fan': 'Fan',
    'profile.edit': 'Bearbeiten',
    'profile.signOut': 'Abmelden',
    'profile.save': 'Speichern',
    'profile.noBio': 'Noch keine Biografie. Klicke auf Bearbeiten um eine hinzuzufügen.',
    'profile.bioPlaceholder': 'Erzähl uns etwas über dich...',
    'profile.votingCredits': 'Voting-Credits',
    'profile.availableForVoting': 'Verfügbar zum Abstimmen',
    'profile.votingHistory': 'Voting-Verlauf',
    'profile.totalVotesCast': 'Gesamte abgegebene Stimmen',
    'profile.favorites': 'Favoriten',
    'profile.savedTracks': 'Gespeicherte Tracks',
    'profile.earnedBadges': 'Verdiente Abzeichen',
    'profile.profileType': 'Profil-Typ',
    'profile.comingSoon': 'Vollständige Profilverwaltung für Band-, DJ- und Label-Accounts kommt bald.',
    
    'history.title': 'Chart-Verlauf',
    'history.description': 'Historische Chart-Positionen ansehen',
    'history.selectTrack': 'Wähle einen Track',
    'history.week': 'Woche',
    'history.noData': 'Keine historischen Daten verfügbar',
    
    'profile.title': 'Profil',
    'profile.username': 'Benutzername',
    'profile.email': 'E-Mail',
    'profile.memberSince': 'Mitglied seit',
    'profile.totalVotes': 'Gesamte Stimmen',
    'profile.customCharts': 'Eigene Charts',
    'profile.settings': 'Einstellungen',
    'profile.language': 'Sprache',
    'profile.saveChanges': 'Änderungen speichern',
    
    'about.title': 'Über Dark Charts',
    'about.description': 'Unabhängige Musik-Charts für die Metal & Gothic-Szene',
    'about.mission': 'Unsere Mission',
    'about.missionText': 'Unabhängige Musik-Charts für Heavy Metal, Gothic, Dark Wave und EBM-Szene. Fair, transparent und frei von Pay-to-Win-Mechaniken.',
    'about.noPayToPlay': 'Kein Pay-To-Play',
    'about.noPayToPlayText': 'Künstler zahlen nicht für Rankings. Die Platzierungen werden ausschließlich durch authentische Fan-Stimmen, Expertenrezensionen und Streaming-Engagement bestimmt.',
    'about.howItWorks': 'Wie das Voting funktioniert',
    'about.fanCharts': 'Fan-Charts',
    'about.fanChartsText': 'Community-gesteuerte Rankings mit quadratischem Voting. Jeder authentifizierte Benutzer erhält monatlich Voting-Credits, um seine Lieblingskünstler zu unterstützen.',
    'about.expertCharts': 'Experten-Charts',
    'about.expertChartsText': 'Kuratiert von DJs, Produzenten und Musikjournalisten mit Bayesschen Ranking-Algorithmen. Experten-Reputationswerte gewährleisten qualitativ hochwertige Bewertungen.',
    'about.streamingCharts': 'Streaming-Charts',
    'about.streamingChartsText': 'Normalisierte Streaming-Daten von Spotify und YouTube, gewichtet nach Hörer-Loyalität statt bloßen Wiedergabezahlen.',
    'about.principles': 'Grundsätze',
    'about.principle1': 'Keine Pay-to-Play-Mechaniken',
    'about.principle2': 'Community-gesteuerte Rankings',
    'about.principle3': 'Transparente Methodik',
    'about.principle4': 'Szene-fokussierte Kuration',
    'about.principle5': 'Schutz vor Manipulation',
    'about.builtFor': 'Von Fans für Fans gebaut. Unterstützung von Underground-Künstlern durch faire Repräsentation und authentisches Community-Engagement.',
    
    'footer.tagline': 'Unabhängige Musik-Charts für die Metal & Gothic-Szene. Fair, transparent und frei von Pay-to-Win-Mechaniken.',
    'footer.underground': 'Underground stirbt nie',
    
    'common.loading': 'Lädt...',
    'common.error': 'Fehler',
    'common.close': 'Schließen',
    'common.back': 'Zurück',
    'common.viewDetails': 'Details ansehen',
    'common.genres': 'Genres',
    'common.all': 'Alle',
    'common.search': 'Suchen',
    'common.filter': 'Filtern',
    'common.sort': 'Sortieren',
    'common.ascending': 'Aufsteigend',
    'common.descending': 'Absteigend',
    
    'header.subtitle': 'Metal • Gothic • Alternative • Dark Electro',
    
    'admin.title': 'Artist-Verwaltung',
    'admin.subtitle': 'Verwalte Artists und synchronisiere Releases',
    'admin.addArtist': 'Artist hinzufügen',
    'admin.editArtist': 'Artist bearbeiten',
    'admin.sync': 'Sync',
    'admin.syncAll': 'Alle synchronisieren',
    'admin.delete': 'Löschen',
    'admin.edit': 'Bearbeiten',
    'admin.viewReleases': 'Releases ansehen',
    'admin.releases': 'Releases',
    'admin.tracks': 'Tracks',
    'admin.nextSync': 'Nächster Sync',
    'admin.releasesFor': 'Releases für',
    'admin.status.syncing': 'Synchronisiert',
    'admin.status.success': 'Erfolgreich',
    'admin.status.error': 'Fehler',
    'admin.form.name': 'Artist-Name',
    'admin.form.spotifyId': 'Spotify Artist ID',
    'admin.form.genres': 'Genres',
    'admin.form.genresHelp': 'Komma-getrennte Liste',
    'admin.form.artwork': 'Artwork-URL',
    'admin.form.bio': 'Biografie',
    'admin.form.save': 'Speichern',
    'admin.form.cancel': 'Abbrechen',
    'admin.confirm.deleteArtist': 'Bist du sicher, dass du diesen Artist und alle Releases löschen möchtest?',
    'admin.confirm.syncAll': 'Bist du sicher, dass du alle Artists synchronisieren möchtest? Dies kann eine Weile dauern.',
    'admin.success.artistCreated': 'Artist erfolgreich erstellt',
    'admin.success.artistUpdated': 'Artist erfolgreich aktualisiert',
    'admin.success.artistDeleted': 'Artist erfolgreich gelöscht',
    'admin.success.syncCompleted': 'Synchronisation erfolgreich abgeschlossen',
    'admin.success.syncAllCompleted': 'Alle Artists erfolgreich synchronisiert',
    'admin.error.loadArtists': 'Fehler beim Laden der Artists',
    'admin.error.loadReleases': 'Fehler beim Laden der Releases',
    'admin.error.createArtist': 'Fehler beim Erstellen des Artists',
    'admin.error.updateArtist': 'Fehler beim Aktualisieren des Artists',
    'admin.error.deleteArtist': 'Fehler beim Löschen des Artists',
    'admin.error.syncFailed': 'Synchronisation fehlgeschlagen',
    'admin.error.syncAllFailed': 'Synchronisation aller Artists fehlgeschlagen',
    'admin.info.syncStarted': 'Synchronisation gestartet',
    'admin.info.syncAllStarted': 'Synchronisiere alle Artists...',
    'nav.admin': 'Admin',
  }
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useKV<Language>('app-language', 'de');

  const t = (key: string): string => {
    const currentLang = language || 'de';
    return translations[currentLang][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language: language || 'de', setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}
